org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_mappings_version=[VERSIONED]
minecraft_version_range=[VERSIONED]
neo_version=[VERSIONED]
loader_version_range=[1,)
mod_id=rewithered
mod_name=Rewithered
mod_license=MIT
mod_version=1.0.1
mod_group_id=me.pajic.rewithered
mod_authors=pajic
mod_description=Adds wither potions and arrows and integrates them into the world
fzzy_version=[VERSIONED]
mixson_version=v1.4.0